name: Scanning for secrets in commits
on:
 pull_request:
    branches:
      - master
jobs:
  Scan_Secrets_in_commit:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # actions/checkout@v4 | releases,v4.3.1
      with:
        fetch-depth: 10
    - name: Secret Scanning
      uses: trufflesecurity/trufflehog@648aca62d5437454d477426fb20c29f402c06a4e # trufflesecurity/trufflehog@main
      with:
        extra_args: --exclude-paths=.script/SecretScanning/Excludepathlist --only-verified
