name: Lint

permissions:
  contents: read

on: [push, pull_request]

jobs:
  all-json-valid:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # actions/checkout@v6 | v6.0.2
    - name: Lint Valid Json
      run: |
        find quirks/ -name '*.json' -print0 -maxdepth 1 | while IFS= read -r -d '' filename; do
          echo "Validating $(basename "$filename")"
          python -mjson.tool "$filename" > /dev/null
        done

  change-password-urls:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # actions/checkout@v6 | v6.0.2
    - name: Lint Sort Order
      run: cat quirks/change-password-URLs.json | sed '1,1d' | sed '$d' | sort -c

  password-rules:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # actions/checkout@v6 | v6.0.2
    - name: Lint Sort Order
      run: cat quirks/password-rules.json | grep "^    \"" | sort -c

  websites-shared-credentials:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # actions/checkout@v6 | v6.0.2
    - name: Set up Ruby
      uses: ruby/setup-ruby@09a7688d3b55cf0e976497ff046b70949eeaccfd # ruby/setup-ruby@v1 | v1.288.0
      with:
        ruby-version: 2.6
    - name: Lint Sort Order
      run: ruby .github/workflows/lint-scripts/websites-shared-credentials-sort-order.rb
    - name: Lint Duplicates
      run: ruby .github/workflows/lint-scripts/websites-shared-credentials-duplicates.rb

  validate-schemas:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # actions/checkout@v6 | v6.0.2
    - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # actions/setup-node@v6 | main,v6.3.0
    - name: Install ajv-cli
      run: npm install -g ajv-cli
    - name: Validate JSONs against their schemas
      run: ./tools/validate-json-schemas.sh
