name: AWS CodeBuild CI Integration Tests
on:
  pull_request:
  merge_group:
  push:
    branches:
      - master

permissions:
  id-token: write

jobs:
  integration-tests:
    if: github.repository == 'aws/aws-sdk-java-v2'
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@8df5847569e6427dd6c4fb1cf565c83acfa8afa7 # aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ secrets.CI_AWS_ROLE_ARN }}
          aws-region: us-west-2
          role-duration-seconds: 7200
      - name: Run Integration Test build
        uses: aws-actions/aws-codebuild-run-build@4d15a47425739ac2296ba5e7eee3bdd4bfbdd767 # aws-actions/aws-codebuild-run-build@v1 | v1.0,v1.0.18
        timeout-minutes: 180
        with:
          project-name: aws-sdk-java-v2-IntegrationTest-JDK8
          hide-cloudwatch-logs: true

