name: CFN Nag

on:
  workflow_dispatch:
  push:
    paths:
    - "test_infra/**"
    branches:
    - main
  pull_request:
    paths:
    - "test_infra/**"
    branches:
    - main

permissions:
  contents: read

env:
  CDK_DEFAULT_ACCOUNT: 111111111111
  CDK_DEFAULT_REGION: us-east-1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # actions/checkout@v6 | v6.0.2
      - name: Use Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # actions/setup-node@v6 | main,v6.3.0
        with:
          node-version: 18
      - name: Cache Node.js modules
        uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # actions/cache@v5 | v5.0.3
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-
            ${{ runner.OS }}-
      - name: Install CDK 
        run: |
          npm install -g aws-cdk
          cdk --version
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # actions/checkout@v6 | v6.0.2
      - name: Set up Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # actions/setup-python@v6 | main,v6.2.0
        with:
          python-version: 3.11
      - name: Rust latest
        run: rustup update
      - name: Install uv
        uses: astral-sh/setup-uv@5a095e7a2014a4212f075830d4f7277575a9d098 # astral-sh/setup-uv@v7
        with:
          enable-cache: true
      - name: Set up cdk.json
        run: |
          cd test_infra
          cat <<EOT >> cdk.context.json
          {
            "availability-zones:account=111111111111:region=us-east-1": [
              "us-east-1a",
              "us-east-1b",
              "us-east-1c",
              "us-east-1d",
              "us-east-1e",
              "us-east-1f"
            ]
          }
          EOT
          cat cdk.json | jq -r '.context.databases.neptune = true' | jq -r '.context.databases.oracle = true' | jq -r '.context.databases.sqlserver = true' > overwrite.cdk.json
          rm cdk.json && mv overwrite.cdk.json cdk.json
      - name: CDK Synth
        run: |
          cd test_infra
          uv sync --frozen --no-install-project --verbose
          uv run cdk synth
        working-directory: ${{ github.workspace }}
      - uses: stelligent/cfn_nag@8b5f03da74202ba323a145e9d037ddce6cab9dec # stelligent/cfn_nag@master
        with:
          input_path: test_infra/cdk.out
          extra_args: --ignore-fatal
