name: Check examples

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # actions/checkout@v6 | v6.0.2
      - uses: dtolnay/rust-toolchain@631a55b12751854ce901bb631d5902ceb48146f7 # dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@779680da715d629ac1d338a641029a2f4372abb5 # Swatinem/rust-cache@v2

      - name: Check examples
        working-directory: examples
        shell: bash
        run: ./check-examples.sh
