name: Static Checking

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  Check:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # actions/checkout@v6 | v6.0.2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # actions/setup-python@v6 | main,v6.2.0
        with:
          python-version: ${{ matrix.python-version }}
      - name: Rust latest
        run: rustup update
      - name: Install uv
        uses: astral-sh/setup-uv@5a095e7a2014a4212f075830d4f7277575a9d098 # astral-sh/setup-uv@v7
        with:
          enable-cache: true
      - name: Install Requirements
        run: uv sync --frozen --all-extras --dev --verbose
        working-directory: ${{ github.workspace }}
      - name: Run ruff format
        run: uv run ruff format --check .
        working-directory: ${{ github.workspace }}
      - name: Run ruff check
        run: uv run ruff check --output-format=github .
        working-directory: ${{ github.workspace }}
      - name: Run mypy check
        run: uv run mypy --install-types --non-interactive awswrangler
        working-directory: ${{ github.workspace }}
      - name: Run documentation check
        run: uv run doc8 --max-line-length 120 docs/source
        working-directory: ${{ github.workspace }}
      - name: Run uv lock check
        run: uv lock --check
        working-directory: ${{ github.workspace }}
