name: OpenBSD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  merge_group:
    types: [checks_requested]
    branches: [main]

permissions:
  contents: read

jobs:
  testopenbsd:
    runs-on: ubuntu-latest
    name: CI OpenBSD
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # actions/checkout@v6 | v6.0.2
      - name: Build and test in OpenBSD
        id: test
        uses: cross-platform-actions/action@492b0c80085400348c599edace11141a4ee73524 # cross-platform-actions/action@v0.32.0
        with:
          operating_system: openbsd
          architecture: x86-64
          version: '7.4'
          cpu_count: 4
          shell: bash
          run: |
            sudo pkg_add ninja cmake
            pkg_info
            sysctl -n kern.version
            .github/s2n_bsd.sh
      - name: upload test results
        if: ${{ failure() }}
        uses: actions/upload-artifact@0c366cb4fc8897159c94880f94b55bc716ad6a66 # actions/upload-artifact@master
        with:
          name: all_test_output
          path: |
            output
