name: Publish to PyPI

on:
  release:
    types: [published]

jobs:
  publish-to-pypi:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # actions/checkout@v4 | releases,v4.3.1
    - name: Get tags
      run: git fetch --tags origin
    - uses: actions/setup-python@7f4fc3e22c37d6ff65e88745f38bd3157c663f7c # actions/setup-python@v4 | restore-v4-release,v4.9.1
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install -U pip
        python -m pip install setuptools wheel
    - name: Create `dist` folder
      run: |
        python setup.py sdist bdist_wheel
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@ed0c53931b1dc9bd32cbe73a98c7f6766f8a527e # pypa/gh-action-pypi-publish@release/v1 | release
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
        skip_existing: true
