name: Review dependencies

on:
  pull_request:
    branches: ['main', 'release/**']
    paths:
      - 'ecr-login/go.*'

jobs:
  review:
    runs-on: ubuntu-latest

    permissions:
      # Write permissions needed to comment review results on PR.
      # Pwn request risk mitigated by using pull_request workflow trigger
      # and external contributor workflow runs require maintainer approval.
      pull-requests: write

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # actions/checkout@v6 | v6.0.2
      - uses: actions/dependency-review-action@2031cfc080254a8a887f58cffee85186f0e49e48 # actions/dependency-review-action@v4 | main,v4.9.0
        with:
          config-file: './.github/dependency-review-config.yml'
          comment-summary-in-pr: always
