name: Scanning for secrets in commits
on:
 pull_request:
    branches:
      - master
jobs:
  Scan_Secrets_in_commit:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # actions/checkout@v4 | releases,v4.3.1
      with:
        fetch-depth: 10
    - name: Secret Scanning
      uses: trufflesecurity/trufflehog@c3e599b7163e8198a55467f3133db0e7b2a492cb # trufflesecurity/trufflehog@main | v3.93.7
      with:
        extra_args: --exclude-paths=.script/SecretScanning/Excludepathlist --only-verified
