name: Lexical Integration Tests

on:
  workflow_call:

permissions: {}

jobs:
  integration:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]
    env:
      CI: true
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # actions/checkout@v4 | releases,v4.3.1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # actions/setup-node@v4 | releases,v4.4.0
        with:
          node-version: ${{ matrix.node-version }}
      - uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # pnpm/action-setup@v4
        with:
          version: 9
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - run: pnpm run test-integration
