name: lint_python
on:
  pull_request:
    branches: main
  push:
    branches: main
jobs:
  lint_python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # actions/checkout@v2 | releases,850,v2.7.0
      - uses: actions/setup-python@e9aba2c848f5ebd159c070c61ea2c4e2b122355e # actions/setup-python@v2 | releases,v2.3.4
      - run: pip install bandit click==8.0.4 black==22.3.0 codespell flake8 isort pyre-check pytest pyupgrade
      - run: bandit --recursive --skip B101,B301,B303,B311,B324,B403,B613 .
      - run: black --check .
      - run: codespell --ignore-words-list="tha" --skip="*/text_tests,*assets/text/*,*examples/*,*/text/augmenters/utils.py"
      - run: flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
      - run: flake8 . --count --exit-zero --max-complexity=15 --max-line-length=90 --show-source --statistics
      - run: isort --check-only --profile black . || true
      - run: shopt -s globstar && pyupgrade --py36-plus **/*.py || true
