name: tests

on:
  push:
    branches:
      - 'main'
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  flow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # actions/checkout@v6 | v6.0.2
      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # actions/setup-node@v6 | main,v6.3.0
        with:
          node-version: '22.x'
          cache: 'yarn'
          cache-dependency-path: yarn.lock
      - run: corepack prepare yarn@1.22.22 --activate
      - run: yarn install --frozen-lockfile
      - run: yarn flow

  packages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # actions/checkout@v6 | v6.0.2
      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # actions/setup-node@v6 | main,v6.3.0
        with:
          node-version: '22.x'
          cache: 'yarn'
          cache-dependency-path: yarn.lock
      - run: corepack prepare yarn@1.22.22 --activate
      - run: yarn install --frozen-lockfile
      - run: yarn test:packages

  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # actions/checkout@v6 | v6.0.2
      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # actions/setup-node@v6 | main,v6.3.0
        with:
          node-version: '22.x'
          cache: 'yarn'
          cache-dependency-path: yarn.lock
      - run: corepack prepare yarn@1.22.22 --activate
      - run: yarn install --frozen-lockfile
      - run: yarn prettier:report

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # actions/checkout@v6 | v6.0.2
      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # actions/setup-node@v6 | main,v6.3.0
        with:
          node-version: '22.x'
          cache: 'yarn'
          cache-dependency-path: yarn.lock
      - run: corepack prepare yarn@1.22.22 --activate
      - run: yarn install --frozen-lockfile
      - run: yarn lint:report

  spelling:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # actions/checkout@v6 | v6.0.2
      - uses: crate-ci/typos@ba7fb02d4a75d0e23458a33f08f927b66caaab2a # crate-ci/typos@master
        with:
          config: .github/workflows/typos.toml
