name: audiocraft_tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, audiocraft_pub_main ]

jobs:
  run_tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # actions/checkout@v2 | releases,850,v2.7.0
      - uses: ./.github/actions/audiocraft_build
      - name: Run unit tests
        run: |
          . env/bin/activate
          make tests
      - name: Run integration tests
        run: |
          . env/bin/activate
          make tests_integ
