name: Continuous Releases

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # actions/checkout@v2 | releases,850,v2.7.0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # actions/setup-node@v3 | releases,v3.9.1
        with:
          node-version: 20.x
          cache: yarn
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Preview
        run: npx pkg-pr-new@0.0.24 publish --compact
