name: Boilerplate

on:
  pull_request:
    branches: ['main']

jobs:

  check:
    name: Boilerplate Check
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false # Keep running if one leg fails.
      matrix:
        extension:
        - go
        - sh

        # Map between extension and human-readable name.
        include:
        - extension: go
          language: Go
        - extension: sh
          language: Bash

    steps:
      - name: Check out code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # actions/checkout@v6 | v6.0.2

      - uses: chainguard-dev/actions/boilerplate@fc204518190e8e1288f6948a9c7871e4701c3852 # chainguard-dev/actions/boilerplate@main
        with:
          extension: ${{ matrix.extension }}
          language: ${{ matrix.language }}
