name: Python Fire

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["macos-latest", "ubuntu-latest"]
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12", "3.13", "3.14.0-rc.2"]
        include:
          - {os: "ubuntu-22.04", python-version: "3.7"}

    steps:
     # Checkout the repo.
     - name: Checkout Python Fire repository
       uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # actions/checkout@v4 | releases,v4.3.1

     # Set up Python environment.
     - name: Set up Python ${{ matrix.python-version }}
       uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # actions/setup-python@v5 | releases,v5.6.0
       with:
         python-version: ${{ matrix.python-version }}

     # Build Python Fire using the build.sh script.
     - name: Run build script
       run: ./.github/scripts/build.sh
       env:
         PYTHON_VERSION: ${{ matrix.python-version }}
