# Build Docsy & the website and run all repo checks across OSs.
# cSpell:ignore docsy

name: test

on:
  push:
    branches: [main]
  pull_request:
  # schedule:
  #   - cron: '11 0 * * *' # 11 past midnight every day
  workflow_dispatch:
permissions:
  contents: read
  
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # actions/checkout@v6 | v6.0.2

      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # actions/setup-node@v6 | main,v6.3.0
        with:
          node-version-file: .nvmrc
          cache: npm
          cache-dependency-path: package.json

      - run: npm install --omit=optional

      - if: runner.os != 'Windows'
        run: npm run ci:test

      - if: runner.os == 'Windows'
        run: npm run ci:prepare && npm run cd:docsy.dev build && npm run ci:post

      - uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # actions/upload-artifact@v6 | v6.0.0
        with:
          name: test-site-${{ matrix.os }}
          path: |
            docsy.dev/public
