name: amd64 MacOS Zig

on: [push, pull_request]

jobs:
  run:
    strategy:
      matrix:
        target:
          - x86_64-macos-none
    runs-on: macos-15-intel  # Using x86 processors
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # actions/checkout@v6 | v6.0.2
      - uses: mlugg/setup-zig@d1434d08867e3ee9daa34448df10607b98908d29 # mlugg/setup-zig@v2 | main,v2.2.1
        with:
          version: latest
      - name: Build
        run: zig build -Dtarget=${{ matrix.target }}
      - name: Run list_cpu_features
        run: ./zig-out/bin/list_cpu_features --json
