name: npm cli check
on:
    workflow_dispatch:
    schedule:
        - cron: "0 0 * * *"
jobs:
    ubuntu:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # actions/setup-node@v4 | releases,v4.4.0
              with:
                  node-version: "22"
            - run: npx --yes genaiscript --help
    windows:
        runs-on: windows-latest
        steps:
            - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # actions/setup-node@v4 | releases,v4.4.0
              with:
                  node-version: "22"
            - run: npx --yes genaiscript --help
    macos:
        runs-on: macos-latest
        steps:
            - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # actions/setup-node@v4 | releases,v4.4.0
              with:
                  node-version: "22"
            - run: npx --yes genaiscript --help
