name: Pylint

on:
  pull_request:
    paths:
      - src/promptflow-evals/**

jobs:
  run_pylint:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # actions/checkout@v2 | releases,850,v2.7.0

      - name: setup python
        uses: actions/setup-python@e9aba2c848f5ebd159c070c61ea2c4e2b122355e # actions/setup-python@v2 | releases,v2.3.4
        with:
          python-version: 3.9

      - uses: snok/install-poetry@76e04a911780d5b312d89783f7b1cd627778900a # snok/install-poetry@v1 | master,v1.4,v1.4.1
      - name: install pylint and azure-pylint-guidelines-checker
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: |
          set -xe
          poetry install -C src/promptflow-evals --with dev
          poetry show -C src/promptflow-evals
      - name: run pylint
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: |
          cd src/promptflow-evals
          poetry run pylint promptflow/evals --rcfile=../../pylintrc
