name: Badge - Azure

on:
  workflow_run:
    workflows:
      - Examples - Azure
    types: [completed]

  workflow_dispatch:

permissions:
  actions: read
  contents: read

jobs:
  badge:
    if: ${{ github.event_name == 'workflow_dispatch' || (github.event_name == 'workflow_run' && github.event.workflow_run.head_branch == 'main') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # actions/checkout@v6 | v6.0.2
      - uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # actions/github-script@v8 | v8.0.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const badgeAggregation = require('./scripts/badge_aggregation.js');
            const dependencies = [
              { workflow: 'examples-azure.yml', label: 'azure', variants: ['stable'] },
            ];
            await badgeAggregation({ github, context, core, dependencies });
