name: Release

on:
  release:
    types:
      - created

jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # actions/checkout@v2 | releases,850,v2.7.0
      - name: Install Node.js
        uses: actions/setup-node@f1f314fca9dfce2769ece7d933488f076716723e # actions/setup-node@v1 | servicing,v1.4.6
        with:
          node-version: 14.x
      - run: npm install
      - name: Publish to VS Marketplace
        run: npx vsce publish
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
