name: Read and Echo Files

on:
    workflow_dispatch:

jobs:
    read_and_echo:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # actions/checkout@v4 | releases,v4.3.1
            - name: Read and echo files
              run: |
                  for file in $(ls | head -n 10); do
                      echo "Contents of $file:"
                      cat "$file"
                      echo ""
                  done
