name: Build Website

on:
  workflow_call:
    outputs:
      build-path:
        description: "Path to the build directory"
        value: ${{ jobs.build.outputs.build-path }}

jobs:
  build:
    name: "Build the website"
    runs-on: ubuntu-24.04
    outputs:
      build-path: ./build
    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # actions/checkout@v4 | releases,v4.3.1
      - name: Setup Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # actions/setup-node@v4 | releases,v4.4.0
        with:
          node-version: '22'
      - name: Install dependencies
        run: yarn
        working-directory: ./docsite
      - name: Build website
        run: yarn build
        working-directory: ./docsite
      - name: Upload build artifacts
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # actions/upload-artifact@v4 | v4.6.2
        with:
          name: website-build
          path: ./docsite/build
          retention-days: 1
