name: 'PR description checker'
on:
  pull_request_target:
    types:
      - opened
      - edited
      - reopened
      - labeled
      - unlabeled
jobs:
  check-pr-description:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # actions/checkout@v2 | releases,850,v2.7.0
      - uses: jadrol/pr-description-checker-action@c659fed338a52d657d34462c8bc7fc1f65d25758 # jadrol/pr-description-checker-action@v1.0.0
        id: description-checker
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
