name: Verify labels
on:
  pull_request:
    branches:
      - "main"
    paths:
      - "package.json"
      - "eng/common/config/"
      - "eng/common/labels/"
      - ".github/workflows/sync-labels.yml"
      - "CONTRIBUTING.md"

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # actions/checkout@v4 | releases,v4.3.1
      - uses: ./.github/actions/setup

      - run: pnpm install
        name: Install dependencies

      - run: pnpm sync-labels --github --check
        name: Verify labels
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
