name: Test Harness

on:
  push:
    branches:
      - main
      - release-*
  pull_request:
    branches:
      - main
      - release-*

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # actions/checkout@v5 | releases,v5.0.1
      - name: Setup .NET Core
        uses: actions/setup-dotnet@baa11fbfe1d6520db94683bd5c7a3818018e4309 # actions/setup-dotnet@v5 | v5.1.0
        with:
          dotnet-version: 8.0.x
      - uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # actions/setup-node@v5 | releases,v5.0.0
        with:
          node-version: 22
      - name: Install prerequisites and download drivers
        shell: bash
        run: ./build.sh --download-driver
      - name: Building
        run: dotnet build ./src
      - name: Installing Browsers and dependencies
        run: pwsh src/Playwright/bin/Debug/netstandard2.0/playwright.ps1 install --with-deps
      - name: Install test-runner
        run: npm ci
        working-directory: src/Playwright.TestingHarnessTest
      - name: Running tests
        run: xvfb-run npx playwright test
        working-directory: src/Playwright.TestingHarnessTest
