# 国际标准时间+8
# 每天issue和pr的关闭情况
name: issues-dailyclose-schedule

on:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * *"

jobs:
  create-report:
    # prevents this action from running on forks
    if: github.repository == 'Tencent/tdesign' 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # actions/checkout@v4 | releases,v4.3.1
      - uses: TDesignOteam/create-report@dfc9b5437db0ac494e652a80a77f58e50c3275dd # TDesignOteam/create-report@main
        with:
          wxhook: ${{ secrets.WX_HOOK_URL }}
          token: ${{ secrets.GIT_TOKEN_L }}
          type: 'close'
