on:
  pull_request_target:
    types:
      - opened
      - reopened
    branches:
      - 'main'
name:
  team-label
permissions:
  pull-requests: write

jobs:
  team-labeler:
    runs-on: ubuntu-latest
    steps:
      - uses: JulienKode/team-labeler-action@edc2a1d3b252624ac7611293835edad9f1392ed4 # v2.0.2
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"

