name: Review dependencies

on:
  pull_request:
    branches: ['main', 'release/**']
    paths:
      - 'ecr-login/go.*'

jobs:
  review:
    runs-on: ubuntu-latest

    permissions:
      # Write permissions needed to comment review results on PR.
      # Pwn request risk mitigated by using pull_request workflow trigger
      # and external contributor workflow runs require maintainer approval.
      pull-requests: write

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: actions/dependency-review-action@05fe4576374b728f0c523d6a13d64c25081e0803 # v4
        with:
          config-file: './.github/dependency-review-config.yml'
          comment-summary-in-pr: always
