name: XGBoost Tests

on: [push, pull_request]

jobs:
  test:
    strategy:
      max-parallel: 4
      fail-fast: false
      matrix:
        python-version: ['3.11']
        platform: [ubuntu-latest]

    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@7f4fc3e22c37d6ff65e88745f38bd3157c663f7c # v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install other dependencies
      run: |
        pip install "Cython<3.0"
        pip install . \
          -r requirements/requirements-test.txt \
          -r requirements/requirements-rotbaum.txt \
          -r requirements/requirements-rotbaum-extra-methods.txt
    - name: Test with pytest
      run: |
        pytest -n2 --timeout 120 --doctest-modules test/ext/rotbaum
