name: Increment Version
on:
  workflow_call:
    inputs:
      increment:
        required: true
        type: string
      dry-run:
        required: true
        type: boolean
      channel:
        required: true
        type: string
    outputs:
      version:
        description: 'The new package.json version, e.g. "0.16.0"'
        value: ${{ jobs.release.outputs.version }}
      tag-ref:
        description: 'The fully qualified ref for the tag, e.g. "refs/tags/v0.16.0"'
        value: ${{ jobs.release.outputs.tag-ref }}
      latest-release:
        description: 'The latest release (per GitHub releases) prior to this increment, e.g. "v0.15.0"'
        value: ${{ jobs.release.outputs.latest-release }}

jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.increment-version.outputs.version }}
      tag-ref: ${{ steps.increment-version.outputs.tag-ref }}
      latest-release: ${{ steps.latest.outputs.release }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          fetch-depth: 0
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: 22.x
          registry-url: 'https://registry.npmjs.org'
      - uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4
        with:
          version: 9
      - run: pnpm install --frozen-lockfile
      - run: |
          git config user.name "Lexical GitHub Actions Bot"
          git config user.email "<>"
      - id: latest
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          owner: facebook
          repo: lexical
          excludes: draft
      - id: increment-version
        run: pnpm run increment-version
        env:
          # These are passed in the environment as they are used by
          # the postversion script
          INCREMENT: ${{ inputs.increment }}
          CHANNEL: ${{ inputs.channel }}
          LATEST_RELEASE: ${{ steps.latest.outputs.release }}
          DRY_RUN: ${{ inputs.dry-run && '1' || '' }}
