name: Fidelity tests

on: pull_request

jobs:
  compare_renders:
    runs-on: ubuntu-latest
    timeout-minutes: 90

    steps:
    - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      with:
        submodules: true

    - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4

    - name: NPM install
      run: npm ci

    # - name: Lint TypeScript sources
    #   run: npm run lint

    - name: Build packages
      run: |
       npm run build --workspace=@google/model-viewer --workspace=@google/model-viewer-render-fidelity-tools

    - name: Fidelity tests
      uses: coactions/setup-xvfb@b6b4fcfb9f5a895edadc3bc76318fae0ac17c8b3 # v1
      with:
        run: npm run test --workspace=@google/model-viewer-render-fidelity-tools -- --quiet
