name: Docker Images

on:
  push:
    branches: [ master ]
    paths:
      - 'docker/**'
  workflow_dispatch:

permissions:
  packages: write
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - image: standard
            platforms: linux/amd64,linux/arm64
          - image: riscv
            platforms: linux/amd64
          - image: android
            platforms: linux/amd64
          - image: sme2
            platforms: linux/arm64
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Set up QEMU
        uses: docker/setup-qemu-action@c7c53464625b32c7a7e944ae62b3e17d2b600130 # v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3

      - name: Log in to GHCR
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@10e90e3645eae34f1e60eeb005ba3a3d33f178e8 # v6
        with:
          context: .
          file: docker/Dockerfile.${{ matrix.image }}
          platforms: ${{ matrix.platforms }}
          push: true
          tags: |
            ghcr.io/google/xnnpack/${{ matrix.image }}:latest
            ghcr.io/google/xnnpack/${{ matrix.image }}:${{ github.sha }}

