# force copy from tencent/tdesign
name: pr-spell-check
on: [pull_request]

jobs:
  run:
    name: Spell Check with Typos
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - name: Check spelling
        uses: crate-ci/typos@master
        with:
          config: .github/workflows/typos-config.toml
