name: '[docs] markdown documents format lint'

on:
  pull_request:
    branches:
      - main
      - master
      - v3.0-dev
      - v3.0
    paths:
      - '*.md'
      - 'docs/**/*.md'

jobs:
  markdownlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
      - name: setup-node
        uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3
        with:
          node-version: 16.x
          cache: 'npm'
          cache-dependency-path: package-lock.json
      - name: Install
        run: |
          npm install markdown-it@12.3.2 markdownlint-cli@0.31.1
      - name: markdownlint
        run: |
          npm run markdownlint
